### PR TITLE
Events page with users login

### PR DESCRIPTION
**Pull request by JAAR91**
Created an events page that allows users to make events, and send invitations to other users.

Users can create many events and invite many people
Users have a notification section where they can see all the events they were invited to and the status of the events, also it's possible to filter the events by future events or past events.
Users can edit or delete an event, also on each event page users can see all the users invited to the event and the status of the invitation.

### CODE REVIEW

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Guys

THIS IS VERY IMPRESSIVE WORK. YOU HAVE DONE A GOOD JOB :+1:

However, there are some changes that you need to make in order to get your project approved


 - [x] I got this error when I tried to create a new event without specifying the date
err

- [ ] Add a live version for the project

- [x] The event's show page should display the list of attendants [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png) from [Odin](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/associations)

- [x]  When a user is logged in Visit a User's show page lists all the events the user has created

- [x] When a user is logged in Event#index Lists all the existing events separated into Past and Upcoming categories



 - [x] Event has a class method that returns the past events
 - [x] Event has a class method that returns the upcoming events

        ex.
    
        # model
        scope :upcoming_events, -> { where('date >= ?', Date.today) }
        scope :past_events, -> { where('date < ?', Date.today) }
    
    
        # controller
         def show_upcoming
            @upcoming_events = Event.upcoming_events
         end
    
        def show_past
          @past_events = Event.past_events
        end


  - [x] User model: has_many :events, foreign_key: :creator_id
  - [x] Event model belongs_to :creator, class_name: "User"

    Migrations

    - [x] events table has creator_id as the foreign key [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/associations)

            def change
              create_table :users do |t|
              end
    
              create_table :events do |t|
                t.integer :creator_id
              end
            end


- [x] Add unit tests for models associations and validations


Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED** :recycle: :recycle: 

First of all, you deserve extra credit for some of the extra features you implemented. It made your application look really nice. I like it.  :+1: Great job :clap: 

You've also implemented most of the changes requested from the last review. :+1:  Nice effort.

However, you need to make some outstanding changes (specified in the previous review).

- [x] You currently have no user's show page. The user's show page should display events the user has created and events that the user is attending to be separated in past and upcoming.

[OPTIONAL]

- [ ] Add integration tests to event management features as well as authentication. You can make use of Capybara.
- [x] You can also consider deploying on heroku.

Please submit another CRR when you're ready.

If you require any clarification or support, drop your comments here and mention me or hit me up on slack.

**Cheers and happy coding.** :smile:

**Comment by JAAR91** [comment]
Thanks for the review, I want to clarify I do have a page where you can see all the events created for the user logged in, is the link on top of "My Events", I am using the same page as events#index to display the events for that user and also all the Events when on the home page, also you can see all the Events the user is participating in by clicking on notifications, this will display all Events you were invited to and will show you with a color Futur events and past events also you can filter than on the same page,  for this one I used the attendees#index page to display all the events a User is being invited.

**Comment by george-shammar** [comment]
Sorry I'm just seeing this due to time zone differences. 

The events#index page would display all(by all users) events according to categories (upcoming and past). Whereas a user's show page would only display events created and attended or being attended by a specific user. The difference between the two is that the a logged in user would see all events on index page(irrespective of the creator). When I checked your code, I only saw html.erb template to create a new user (no show page).

I hope this clarifies it a bit for you. Let me k ow if you have further questions.

**Review by elisha2kyakpo1 — APPROVED** [review]
# Status: Approved✔🎉
Congratulations! Your project is outstanding, the UI is perfect and the code too. Please keep it up!
I'm happy to see all the changes requested being implemented.
<hr>

Happy coding💪👈✔

**Pull request merged**
